name: Build Android App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Install MAUI
      run: |
        dotnet workload install maui
        dotnet workload install android

    - name: Clean
      run: dotnet clean NumberPlate.csproj

    - name: Restore
      run: dotnet restore NumberPlate.csproj

    - name: Build Android
      run: dotnet build NumberPlate.csproj -f net9.0-android -c Release

    - name: Publish APK
      run: dotnet publish NumberPlate.csproj -f net9.0-android -c Release

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: AndroidAPK
        path: '**/*.apk'
